### PR TITLE
  release:

### PR DESCRIPTION
**Pull request by CallumWalley**
Should build one container for each branch, but also one on releases

### CODE REVIEW

**Comment by jennan** [comment]
@CallumWalley thank you for your contribution. Would it possible to build based on tags instead of releases :)? Tag is the way this package is currently "released" (and this avoids having to go clicking in the github interface to create a new release :P... but maybe it's just me liking a more CLI/vanilla git oriented workflow...).

**Comment by CallumWalley** [comment]
That was the quickest implementation, (because i'm lazy). But I respect you not wanting to press an extra button (because i'm lazy).

**Comment by CallumWalley** [comment]
I assumed you still wanted containers built for branches. Current implementation doesn't.
I guess you can always trigger manually, so no biggie.

@jennan

**Comment by jennan** [comment]
@CallumWalley yeah I didn't realize this is not possible (hence my test using tags 😑)... well it was a good occasion to update the maintenance doc 😄.

**Comment by jennan** [comment]
@CallumWalley I have found a solution to get tags or path mechanism 🎉.
Please let me know if you happy with this and also the maintenance guidelines (I tried to make the steps more explicit and using the builds from github CI) before I merge :).

**Review by CallumWalley — COMMENTED** [review]
Yea, looks fine. We just need to remember not to tag any of the branches.

**Pull request merged**
